name: publish-npm-package

on: 
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          force-depth: 0
          
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Install packages
        run: npm install

      - name: Setup Playwright
        run: npx playwright install --with-deps

      - name: Run tests and build
        run: npm run build

      - name: Publish packages
        working-directory: packages/vue-pdf
        run: npm publish --access public
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
       
      